#!/bin/bash
#SBATCH --job-name trim
#SBATCH -o QQQ.log
#SBATCH --ntasks=16
#SBATCH --mem=200000
#SBATCH --time=72:00:00

set -euo pipefail

# Useful paths
WORKDIR=/path/to/working/directory
DIRLOC="${WORKDIR}/trim"
FASTQS="${WORKDIR}/data"
TOOLS=/path/to/installed_packages

# Change to trim directory
cd ${DIRLOC}

${TOOLS}/trim_galore \
    --no_report_file \
    --basename QQQ_XXXM \
    --cores 4 \
    --paired \
    ${FASTQS}/QQQ_1.fastq.gz \
    ${FASTQS}/QQQ_2.fastq.gz

