#!/bin/bash
#SBATCH --job-name bism_QQQ
#SBATCH -o slurm/bism_QQQ.log
#SBATCH --ntasks=30
#SBATCH --mem=150000
#SBATCH --time=2-00:00:00

set -euo pipefail

WORKDIR=/path/to/working/directory

# Useful paths
DIRLOC=${WORKDIR}/snmc_seq2
REFLOC=${WORKDIR}/refs/bismark
FASTQS=${WORKDIR}/snmc_seq2_data
TOOLS=/path/to/installed_packages

# TOOLS
module load bbc2/bismark/bismark-0.24.0
SAMTOOL=${TOOLS}/samtools_packages_v1.17/make_install_files/bin
BEDTOOL=${TOOLS}/bedtools_2.30.0/bin
TIMEDIR=${TOOLS}/time-1.9

# FILES
REF=${REFLOC}/hg38
FQ1=${FASTQS}/QQQ_trimmed_R1.fastq.gz
FQ2=${FASTQS}/QQQ_trimmed_R2.fastq.gz
OUT=${DIRLOC}/bism_QQQ
TIM=bism_QQQ.gnu_time.tsv
BM1=QQQ_trimmed_R1_bismark_bt2.bam
BM2=QQQ_trimmed_R2_bismark_bt2.bam
DP1=QQQ_trimmed_R1_bismark_bt2.deduplicated.bam
DP2=QQQ_trimmed_R2_bismark_bt2.deduplicated.bam
SR1=QQQ_trimmed_R1_bismark_bt2.deduplicated.name_sorted.bam
SR2=QQQ_trimmed_R2_bismark_bt2.deduplicated.name_sorted.bam
MRG=QQQ.name_sorted.dedup.bam
SRT=QQQ_trimmed_R1_bismark_bt2.sorted.deduplicated.bam
NRD=bism_QQQ.read_counts.txt
TTO=tmp.hg38.QQQ.total_reads
TMP=tmp.hg38.QQQ.mapped_reads
TGM=tmp.hg38.QQQ.good_mapped_reads

# Use the same number of threads throughout
NTHREADS=30

# Create analysis directory if it doesn't exist
mkdir -p ${OUT}

# Change to analysis directory
cd ${OUT}

# /usr/bin/time format string
# part\tuser\tsystem\telapsed\tCPU\ttext\tdata\tmax\tinputs\toutputs\tmajor\tminor\tswaps

# bismark align
# Alignment portion based on: https://github.com/lhqing/cemba_data/blob/master/cemba_data/mapping/Snakefile_template/mc.Snakefile
# Which is from YAP, which was used in the Ecker brain atlas dataset, which uses scnmc-seq2
( ${TIMEDIR}/time \
    --format="align_r1\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    bismark \
    --pbat \
    --parallel 10 \
    --output_dir ${OUT} \
    --temp_dir ${OUT} \
    --samtools_path ${SAMTOOL}/samtools \
    --genome ${REF} \
    ${FQ1}
)

( ${TIMEDIR}/time \
    --format="align_r2\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    bismark \
    --parallel 10 \
    --output_dir ${OUT} \
    --temp_dir ${OUT} \
    --samtools_path ${SAMTOOL}/samtools \
    --genome ${REF} \
    ${FQ2}
)

# bismark dedup
( ${TIMEDIR}/time \
    --format="dedup_r1\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    deduplicate_bismark \
    --output_dir ${OUT} \
    ${BM1}
)

( ${TIMEDIR}/time \
    --format="dedup_r2\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    deduplicate_bismark \
    --output_dir ${OUT} \
    ${BM2}
)

# samtools name sort
( ${TIMEDIR}/time \
    --format="name_sort_r1\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    samtools sort -n -@ "${NTHREADS}" \
    -o ${SR1} -O bam \
    ${DP1}
)

( ${TIMEDIR}/time \
    --format="name_sort_r2\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    samtools sort -n -@ "${NTHREADS}" \
    -o ${SR2} -O bam \
    ${DP2}
)

# samtools merge
( ${TIMEDIR}/time \
    --format="merge\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    samtools merge -n -O BAM -@ "${NTHREADS}" \
    ${MRG} \
    ${SR1} \
    ${SR2}
)

# bismark methylation extraction
( ${TIMEDIR}/time \
    --format="meth_extract\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    bismark_methylation_extractor \
    --multicore 10 \
    --bedGraph \
    --gzip \
    --output ${OUT} \
    ${MRG}
)

# sort and index final bam
( ${TIMEDIR}/time \
    --format="sort\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    ${SAMTOOL}/samtools sort -@ "${NTHREADS}" -m 5G -o ${SRT} -O BAM ${MRG}
)

( ${TIMEDIR}/time \
    --format="index\t%U\t%S\t%e\t%P\t%X\t%D\t%M\t%I\t%O\t%F\t%R\t%W" \
    --output=${TIM} \
    --append \
    ${SAMTOOL}/samtools index -@ "${NTHREADS}" ${SRT}
)

# Count the number of reads in the BAM
${SAMTOOL}/samtools view -F 2304 ${BM1} | cut -f 1 | awk -F"_" '{ print $1 }' > ${TTO}
${SAMTOOL}/samtools view -F 2304 ${BM2} | cut -f 1 | awk -F"_" '{ print $1 }' >> ${TTO}
${SAMTOOL}/samtools view -F 2308 ${BM1} | cut -f 1 | awk -F"_" '{ print $1 }' > ${TMP}
${SAMTOOL}/samtools view -F 2308 ${BM2} | cut -f 1 | awk -F"_" '{ print $1 }' >> ${TMP}
${SAMTOOL}/samtools view -F 2308 -q 40 ${BM1} | cut -f 1 | awk -F"_" '{ print $1 }' > ${TGM}
${SAMTOOL}/samtools view -F 2308 -q 40 ${BM2} | cut -f 1 | awk -F"_" '{ print $1 }' >> ${TGM}

echo -e "total_reads\t`cat ${TTO} | sort -k1 -T ${OUT} | uniq | wc -l`" > ${NRD}
echo -e "mapped_reads\t`cat ${TMP} | sort -k1 -T ${OUT} | uniq | wc -l`" >> ${NRD}
echo -e "good_mapped_reads\t`cat ${TGM} | sort -k1 -T ${OUT} | uniq | wc -l`" >> ${NRD}

# Files to delete
rm ${SRT} ${SRT}.bai
rm ${MRG} ${BM1} ${BM2} ${DP1} ${DP2} ${SR1} ${SR2}
rm *.deduplication_report.txt
rm *_SE_report.txt *.M-bias.txt *.name_sorted.dedup.txt.gz *.name_sorted.dedup_splitting_report.txt
rm ${TTO} ${TMP} ${TGM}
